### ISSUE TITLE
Highlight "Idle" jobs in the Cloud Pipeline API/GUI/CLI

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#624]
1. Cloud Pipeline shall allow to view high-level metrics information for the Active Runs:
- Idle (CPU/Memory consumption is lower than a certain level, defined by the admin) - such runs produce extra costs
- Pressure (CPU/Memory/Disk consumption is higher than a certain level, defined by the admin) - such runs may accidentally fail
2. We shall reuse existing resources monitoring indices and the thresholds that are used for auto-pausing and email notifications
3. Users shall be able to drill-down into the resource consumption metrics (e.g. click "Idle" run and review the resource consumption for the whole job lifetime)
4. Users will be able to sort/filter for idle or pressured runs within a list of active/completed runs
5. The "Idle" or "Pressure" info shall be available for each of the jobs running via:
* GUI
* CLI
* API

**Comment by SilinPavel** [comment]
@Wedds 
First step:
1. Introduce new field Map<String, String> tags for PipelineRun
2. Using Postgre jsonb type functionality change SQL queries to be able to join table metadata for corresponding entity_id and entity_class and select tags (you should select only "tags" field from data column)
3. Change RowMapper from PipelineRunDao to be able to parse and set tags from pipelineRun object

**Comment by SilinPavel** [comment]
@Wedds 
Lets implement the next steps:
1) In the ResourceMonitoringManager change `processRuns` method to set new tag `IDLED=true` or delete previous value if needed to pipelineRun
2) In the ResourceMonitoringManager change `processOverloadedRuns` method to set to runs new tag `PRESSURED=true` or delete previous if needed and collect this runs to list
3) Implement method `updateTags(List<PipelineRun> runs)` for `PipelineRunManager` that will be update tags in DB by batch query (see as example method `updatePipelineRunsLastNotification`)
4) with this method update tags for collected runs in 1) and 2)

**Comment by NShaforostov** [comment]
I've tried to verify this feature.
The following preferences were set:
- `system.max.idle.timeout.minutes` `1`
- `system.idle.cpu.threshold` `50`

In total, six runs were launched at each stand:
- empty DEFAULT pipeline with enabled the `Start idle` checkbox (**On-Demand** with enabled the `Auto pause` checkbox, **On-Demand** with disabled the `Auto pause` checkbox, **Spot**)
- Ubuntu tool (**On-Demand** with enabled the `Auto pause` checkbox, **On-Demand** with disabled the `Auto pause` checkbox, **Spot**)

The following behavior was observed:

**AWS**
Version: 0.16.0.3079.80a336d8d87bdd6125f2a26fef53d2c7923cf119

According to the Node Monitor, CPU Usage for each of the above runs has been being below 5% after 10 minutes from the beginning and didn't rise.
For one of the runs, the tag `IDLE` appeared after about 40 minutes. For most of the runs `IDLE`-tags have appeared after about 1,5 hours. For runs with disabled the `Auto pause` checkbox, `IDLE`-tags haven't appeared at all (after 3 hours).

**AZURE**
Version: 0.16.0.3079.80a336d8d87bdd6125f2a26fef53d2c7923cf119

According to the Node Monitor, CPU Usage for each of the above runs has been being below 30% after 15 minutes from the beginning and didn't rise.
For some of the runs, `IDLE`-tags appeared after about 30 minutes. But then they disappeared without rising the CPU Usage. After about 2 hours `IDLE`-tags have appeared for most of the runs and didn't already disappear. For runs with disabled the `Auto pause` checkbox, `IDLE`-tags haven't appeared at all (after 5 hours).

**GCP**
Version: 0.16.0.2938.b39e1318156277bf71fa30a84ca98506f20522ce

According to the Node Monitor, CPU Usage for each of the above runs has been being below 5% after 10 minutes from the beginning and didn't rise.
After about 25-30 minutes `IDLE`-tags have appeared. For runs with disabled the `Auto pause` checkbox, `IDLE`-tags haven't appeared at all (after 7 hours).

**So, 2 issues should be resolved:**
- `IDLE` tags shall appear not after such a long-time period
- `IDLE` tags appearing shall not depend on setting the `Auto pause` checkbox

Also, could you tell me, **how to view tags via CLI**?

**Comment by NShaforostov** [comment]
**UPD.**
I've additional tried to verify that feature for the `PRESSURE` tag.
It works fine at all stands.

**Comment by SilinPavel** [comment]
@NShaforostov cases with `IDLE` tag should be fixed!

**Comment by NShaforostov** [comment]
@SilinPavel Verified. The issue with a long-time period of `IDLE` tags appearing fixed.

But the second issue still takes place. Currently, the `IDLE` tag doesn't appear if the `Auto pause` checkbox on the launch form was unchecked before the run - it's wrong behavior.

**Comment by mzueva** [comment]
@NShaforostov I hope that the last issue with `Auto pause` runs is fixed. Could you please verify it?

**Comment by NShaforostov** [comment]
@mzueva Verified. The issue with runs with unticked `Auto pause` is fixed.

Another small remark was found - in the following scenario:
1. The run was tagged as `IDLE` (due to set preferences)
  (I have set `system.max.idle.timeout.minutes` - `1` & `system.idle.cpu.threshold` - `50`)
2. System preferences are being changed
  (I have set `system.max.idle.timeout.minutes` - `1` & `system.idle.cpu.threshold` - `1`)
3. **_Exp._**: after some time `IDLE` tag should disappear (because according to the Node Monitor, CPU Usage for the run has been being above 2%).
  **_Act._**: `IDLE` tag doesn't disappear

Such behavior is observed only for `IDLE` tag on `AWS` stand (ver. 0.16.0.3308) and `GCP` stand (ver. 0.16.0.3276)
